"""
Master Template System for System Design Documents.

Provides standardized template và formatting functions.
"""

from datetime import datetime
from typing import Dict, Any


SDD_TEMPLATE = """
# SYSTEM DESIGN DOCUMENT: {feature_name}

**Version**: {version} | **Date**: {date} | **Author**: {author}

---

## 1. OVERVIEW

{business_context}

---

## 2. SYSTEM WORKFLOW (VISUAL)

```mermaid
{mermaid_code}
```

---

## 3. FUNCTIONAL SPECIFICATIONS

### 3.1 Happy Path (Main Flow)

| Step | Action | Description | Output |
|------|--------|-------------|--------|
{workflow_table}

### 3.2 Data Models

```python
{data_schemas}
```

---

## 4. RESILIENCE & EDGE CASES

> **Challenger's Note**: Các kịch bản dưới đây đã được kiểm chứng để đảm bảo tính ổn định của hệ thống.

{edge_cases_list}

---

## 5. TECHNICAL RECOMMENDATIONS

| Component | Technology | Rationale |
|-----------|-----------|-----------|
{tech_stack}

---

*Generated by AI System Design Assistant - Phase 4: Aggregation & Publishing*
""".strip()


def get_mermaid_style_guide() -> str:
    """
    Get Mermaid.js style guide for AI agents.

    Returns:
        str: Style guide with formatting rules
    """
    return """
=== MERMAID.JS STYLE GUIDE ===

1. Định dạng: Sử dụng `graph TD` (Flowchart) hoặc `sequenceDiagram`
2. Node naming:
   - Dùng danh từ ngắn gọn (2-3 từ)
   - PascalCase cho consistency
   - Ví dụ: "ValidateInput" ✅ | "Validating the input data" ❌

3. Edge labeling:
   - Dùng động từ hành động
   - Ví dụ: "sends", "validates", "returns"

4. Styling:
   - Subgraphs cho các nhóm liên quan
   - Màu sắc phân loại:
     * Xanh (#e1f5ff): User/System actions
     * Vàng (#fff4e1): Validation/Decision points
     * Đỏ (#ffe1e1): Error handling

5. Validation:
   - Mã Mermaid phải hợp lệ để render ngay
   - Test tại: https://mermaid.live
""".strip()


def format_sdd(data: Dict[str, Any], template: str = None) -> str:
    """
    Format SDD content với data provided.

    Args:
        data: Dictionary với values để fill vào template
        template: Optional custom template (default: SDD_TEMPLATE)

    Returns:
        str: Formatted SDD markdown content
    """
    if template is None:
        template = SDD_TEMPLATE

    # Set defaults for missing fields
    defaults = {
        "version": "1.0",
        "date": datetime.now().strftime("%Y-%m-%d"),
        "author": "AI Assistant",
        "business_context": "*Business context to be provided*",
        "mermaid_code": "graph TD\nA[Start] --> B[End]",
        "workflow_table": "| Step | Action |",
        "data_schemas": "# Data models to be defined",
        "edge_cases_list": "| Scenario | Behavior | Mitigation |",
        "tech_stack": "| Component | Tech |",
    }

    # Merge data with defaults
    merged = {**defaults, **data}

    return template.format(**merged)
